### ISSUE TITLE
Proper Health Check

### ISSUE THREAD

**Issue by rosskukulinski** [rosskukulinski/kubernetes-rethinkdb-cluster#11]
Should have simple Go binary in the container that connects to Rethink and confirms that db is healthy.

**Comment by paralin** [comment]
Done in #18, sort of. I just curl localhost:8080. But you're right, a better go binary to do it is in order.

**Comment by justinsb** [comment]
What should a more comprehensive health check do?  Willing to write one, but would love to know what we think would be the appropriate checks..

**Comment by rosskukulinski** [comment]
Hi @justinsb!  I was thinking a simple binary that accessed the rethinkdb instance and queried one or more [system tables](https://rethinkdb.com/docs/system-tables/) to verify functionality.

As to _which_ system tables, I haven't fully thought that through.  I don't think we want to report readiness/health check based on the overall cluster availability - we might just be making things worse.

So, then I guess the instance is 'ready' when you can query `server_status` and there's one or more records.

**Comment by tjmehta** [comment]
I would also be willing to write this. Please let us know if you have any more details on this.

**Comment by rosskukulinski** [comment]
first pass of probe complete - thanks @cdornsife
