### ISSUE TITLE
Memory & CPU Limits

### ISSUE THREAD

**Issue by rosskukulinski** [rosskukulinski/kubernetes-rethinkdb-cluster#3]
It might be helpful to specify CPU/Memory requests for our rethink nodes.  If we do so, we should be sure to tell RethinkDB the amount of cache size it has to play with.

https://rethinkdb.com/docs/memory-usage/

```
--cache-size 2048
```

https://github.com/rethinkdb/rethinkdb/issues/5498

**Comment by VerifiedOrganic** [comment]
This would be good, The cache-size gave me a bit of an issue as it ate up my entire 60 gigs of ram.

**Comment by rosskukulinski** [comment]
Implemented in 6f996aa962a45e76d98d64e364e5867826b737a3
