### ISSUE TITLE
GKE/GCE Configuration with persistent storage: What kind of configuration is recommended?

### ISSUE THREAD

**Issue by donjae** [rosskukulinski/kubernetes-rethinkdb-cluster#34]
Hi, 

Just wondering what kind of source type/size is recommended for the persistent disk?

edit: I know size depends, but more so what source type is recommended (image [if so what os] or blank?)

**Comment by rosskukulinski** [comment]
hi @donjae.  You'll want to create a Blank storage disk, preferably SSD for the best performance.
