### ISSUE TITLE
Connection failure for node app to connect to rethinkdb cluster

### ISSUE THREAD

**Issue by donjae** [rosskukulinski/kubernetes-rethinkdb-cluster#35]
Hi, 

I'm deploying my node application on the cluster and getting the following connection error 
```
2017-05-01T19:53:22.005694401Z Fail to create a new connection for the connection pool.
 Error:{"msg":"Failed to connect to localhost:28015\nFull
error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",
\"address\":\"127.0.0.1\",\"port\":28015}","message":
"Failed to connect to localhost:28015\nFull 
```

Is there something wrong with my configuration? No clue on where or how to start to debugging the issue

**Comment by donjae** [comment]
I think it has to do with my application not connecting to the right {internal IP}:28015 in the cluster. Should I setup a separate service for my nodejs app for discovery or something?

**Comment by rosskukulinski** [comment]
@donjae is that connection error from your Node.js application?  If so, then you need to have the nodejs app connect to the `rethinkdb-proxy` service on port 28015.

**Comment by donjae** [comment]
@rosskukulinski Yeah I just figured it out, so I just updated it my node app: 

```
const r = require('rethinkdbdash')({
    servers: [
        {host: {{ip}}, port: 28015}
    ]
});
```
Quick question though, should I write the `{{ip}}` as the cluster IP ( '10.19.254.164 ') or as the intenal endpoint ('rethinkdb-proxy')?
```
Cluster IP: 
    10.10.204.164

Internal endpoints: 
    rethinkdb-proxy:28015 TCP
    rethinkdb-proxy:31443 TCP
```

**Comment by rosskukulinski** [comment]
@donjae you'll want to use the rethinkdb-proxy ClusterIP.  Behind the scenes, Kubernetes will round-robin connections across all of the Proxy endpoints.

**Comment by donjae** [comment]
Thanks, it worked perfectly!
