### ISSUE TITLE
I've created a chart based on your repo

### ISSUE THREAD

**Issue by meenie** [rosskukulinski/kubernetes-rethinkdb-cluster#37]
I wanted to let you know that I've created a Helm Chart roughly based on your current work in this repo.  I mostly borrowed your peer discovery and probe code.  I needed to change it up a bit which is the reason I created my own Docker Image.

https://github.com/meenie/helm-rethinkdb-cluster

If you'd like to collaborate on it, that would be cool :). No worries if not.

**Comment by rosskukulinski** [comment]
hi @meenie!  I've been meaning to do that, so thank you :).  I'll take a deeper look this week.

It would great if you could upstream some of the image tweaks (e.g. adding `RETHINKDB_PASSWORD` to the probe)

**Comment by meenie** [comment]
@rosskukulinski How about you create a separate repo just for the docker image and then I can reference that in the chart?

**Comment by rosskukulinski** [comment]
Sounds good :)

**Comment by rosskukulinski** [comment]
@meenie: https://github.com/rosskukulinski/rethinkdb-kubernetes

I'm also adding you as a collaborator to both projects

**Comment by meenie** [comment]
Great! 👍   I'll create a PR for the recent changes I made to the Docker Image.
