### ISSUE TITLE
Evaluate value of PetSet

### ISSUE THREAD

**Issue by rosskukulinski** [rosskukulinski/kubernetes-rethinkdb-cluster#5]

**Comment by rosskukulinski** [comment]
Waiting for PetSet to leave v1alpha1

**Comment by paralin** [comment]
And now?

**Comment by paralin** [comment]
Done in #18

**Comment by rosskukulinski** [comment]
I believe PetSets are still `apps/v1alpha1`, but I'm happy with how you put them into a separate directory.  Will close this out after I review #18.  👍 💯 🎉

**Comment by rosskukulinski** [comment]
now available
